name: Deploy to App Runner

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de la rama que deseas desplegar

jobs:
  deploy:
    name: Deploy to App Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: AlbertoJBaez/full-stack-deploy@main # Asegúrate de que esté usando la versión correcta
        with:
          service: app-runner-git-deploy-service
          source-connection-arn: ${{ secrets.AWS_CONNECTION_SOURCE_ARN }}
          repo: https://github.com/${{ github.repository }}
          branch: ${{ github.ref }}
          runtime: NODEJS_12
          build-command: npm install
          start-command: npm start
          port: 18000
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          wait-for-service-stability: true

      - name: App Runner output
        run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}"
